name: toolchain
on:
  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  toolchain:
    name: Toolchain
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        platform:
          - hi3516cv100

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build toolchain
        run: |
          echo "8.8.8.8 invisible-mirror.net" | sudo tee -a /etc/hosts
          echo "8.8.8.8 distfiles.dereferenced.org" | sudo tee -a /etc/hosts

          CONFIG=$(find br-ext-chip-* -name ${{matrix.platform}}_lite_defconfig)
          GCC=$(make BOARD=${CONFIG} toolname)
          echo GCC=${GCC} >> ${GITHUB_ENV}
          URL=https://github.com/${GITHUB_REPOSITORY}/releases/download/${TAG_NAME}/${GCC}.tgz
          echo ${URL}
          if ! wget --spider ${URL} 2> /dev/null; then
            sed -i "s|EXTERNAL=y|EXTERNAL=n|g" ${CONFIG}
            make BOARD=${CONFIG} br-sdk
            SDK=$(find output/images -name *_sdk-buildroot.tar.gz)
            mv ${SDK} ${GCC}.tgz
          fi

      - name: Upload toolchain
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.TAG_NAME}}
          files: ${{env.GCC}}.tgz
